close all;
figure(1);
subplot(211);
plot(out.tout,sin(out.tout),'r',out.tout,out.yout{2}.Values.Data(:,1),'k:','linewidth',2);
xlabel('time(s)');ylabel('yd,y');
legend('ideal position','position tracking');
subplot(212);
plot(out.tout,cos(out.tout),'r',out.tout,out.yout{2}.Values.Data(:,2),'k:','linewidth',2);
xlabel('time(s)');ylabel('dyd,dy');
legend('ideal speed','speed tracking');
figure(2);
%plot(t,ut(:,1),'r','linewidth',2);
plot(out.tout,out.yout{3}.Values.Data(:,1),'k:','linewidth',2);
xlabel('time(s)');ylabel('Control input');
figure(3);
subplot(211);
plot(out.tout,out.yout{1}.Values.Data(:,1),'r',out.tout,out.yout{1}.Values.Data(:,4),'k:','linewidth',2);
xlabel('time(s)');ylabel('fx');
legend('True fx','fx estimation');
subplot(212);
plot(out.tout,out.yout{1}.Values.Data(:,2),'r',out.tout,out.yout{1}.Values.Data(:,5),'k:','linewidth',2);
xlabel('time(s)');ylabel('m');
legend('True m','m estimation');