close all; clc;
figure(1);
subplot(211);
plot(out.tout,out.qd.Data(:,1),'r',out.tout,out.q.Data(:,1),'k:','linewidth',2);
xlabel('time(s)');ylabel('Angle tracking for link 1');
legend('ideal angle for link 1','angle tracking for link 1');
subplot(212);
plot(out.tout,out.qd.Data(:,4),'r',out.tout,out.q.Data(:,3),'k:','linewidth',2);
xlabel('time(s)');ylabel('Angle tracking for link 2');
legend('ideal angle for link 2','angle tracking for link 2');
figure(2);
subplot(211);
plot(out.tout,out.qd.Data(:,2),'r',out.tout,out.q.Data(:,2),'k:','linewidth',2);
xlabel('time(s)');ylabel('Speed tracking for link 1');
legend('ideal angle speed for link 1','angle speed tracking for link 1');
subplot(212);
plot(out.tout,out.qd.Data(:,5),'r',out.tout,out.q.Data(:,4),'k:','linewidth',2);
xlabel('time(s)');ylabel('Angle speed tracking for link 2');
legend('ideal angle speed for link 2','angle speed tracking for link 2');
figure(3);
subplot(211);
plot(out.tout,out.tol1.Data(:,1),'k','linewidth',2);
xlabel('time(s)');ylabel('control input of link 1');
subplot(212);
plot(out.tout,out.tol2.Data(:,1),'k','linewidth',2);
xlabel('time(s)');ylabel('control input of link 2');
figure(4);
plot(out.tout,out.f.Data(:,1),'r',out.tout,out.f.Data(:,2),'k:','linewidth',2);
xlabel('time(s)');ylabel('f and fn');
legend('ideal fx','estimation of fx');